import U from"http";import x from"fs";import d from"path";import{fileURLToPath as M,pathToFileURL as k}from"url";function s(t,h={},...w){return{type:t,props:h,children:w}}function j(t){if(typeof t=="string")return t;let h=t.props?Object.entries(t.props).map(([c,a])=>`${c}="${a}"`).join(" "):"",w=t.children?t.children.map(j).join(""):"";return`<${t.type}${h?" "+h:""}>${w}</${t.type}>`}function N(t){let h=M(import.meta.url),w=d.dirname(h),c=process.cwd(),a=t?.pagesDir?d.resolve(t.pagesDir):d.resolve(c,".valzu","pages"),C=t?.publicDir?d.resolve(t.publicDir):d.resolve(c,"public");x.existsSync(a)||(console.error(`\u274C Compiled pages directory not found at ${a}. Please run your build process to compile your pages.`),process.exit(1));let $=x.readdirSync(a).filter(u=>u.endsWith(".js")),g={};$.forEach(u=>{let r=u.replace(/\.js$/,""),v=r==="index"?"/":`/${r}`;g[v]=u});let S=U.createServer(async(u,r)=>{let v=u.url||"/";if(v==="/client.js"){let e=d.resolve(c,".valzu","client.js");x.readFile(e,(i,m)=>{i?(r.statusCode=404,r.end("Not Found")):(r.setHeader("Content-Type","application/javascript"),r.end(m))});return}let o=d.resolve(C,"."+v);if(x.existsSync(o)&&x.statSync(o).isFile()){let e="text/plain",i=d.extname(o);i===".html"?e="text/html":i===".css"?e="text/css":i===".js"&&(e="application/javascript"),x.readFile(o,(m,n)=>{m?(r.statusCode=500,r.end("Internal Server Error")):(r.setHeader("Content-Type",e),r.end(n))});return}if(g[v]!==void 0){try{let e=g[v],i=d.join(a,e),p=(await import(k(i).href)).default;if(!p)throw new Error(`Component not found in ${e}`);let b=await p(),D=j(b),F=d.resolve(C,"index.html"),y=x.readFileSync(F,"utf8");y=y.replace('<div id="app"></div>',`<div id="app">${D}</div>`),y=y.replace("</body>",'<script type="module" src="/client.js"><\/script></body>'),r.setHeader("Content-Type","text/html"),r.end(y)}catch(e){console.error("\u274C Error rendering route:",e),r.statusCode=500,r.end("Internal Server Error")}return}r.statusCode=404,r.end("Not Found")}),E=t?.port||Number(process.env.PORT)||3e3;S.listen(E,()=>{console.log(`\u2705 Production server running on http://localhost:${E}`)})}import A from"http";import f from"fs";import l from"path";import{fileURLToPath as R,pathToFileURL as I}from"url";function P(t){let h=R(import.meta.url),w=l.dirname(h),c=process.cwd(),a=t?.pagesDir?l.resolve(t.pagesDir):l.resolve(c,"pages"),C=t?.publicDir?l.resolve(t.publicDir):l.resolve(c,"public");f.existsSync(a)||(console.error(`\u274C Pages directory not found at ${a}`),process.exit(1));let $=f.readdirSync(a).filter(o=>/\.(ts|tsx)$/.test(o)),g={};$.forEach(o=>{let e=o.replace(/\.(ts|tsx)$/,""),i=e==="index"?"/":`/${e}`;g[i]=o});let S=[],E=A.createServer(async(o,e)=>{let i=o.url||"/";if(i==="/hmr"){e.writeHead(200,{"Content-Type":"text/event-stream","Cache-Control":"no-cache",Connection:"keep-alive"}),e.write(`
`),S.push(e),o.on("close",()=>{let n=S.indexOf(e);n!==-1&&S.splice(n,1)});return}if(i==="/client.js"){let n=l.resolve(c,".valzu/client.js");f.readFile(n,(p,b)=>{p?(e.statusCode=404,e.end("Not Found")):(e.setHeader("Content-Type","application/javascript"),e.end(b))});return}let m=l.resolve(C,"."+i);if(f.existsSync(m)&&f.statSync(m).isFile()){let n="text/plain",p=l.extname(m);p===".html"?n="text/html":p===".css"?n="text/css":p===".js"&&(n="application/javascript"),f.readFile(m,(b,D)=>{b?(e.statusCode=500,e.end("Internal Server Error")):(e.setHeader("Content-Type",n),e.end(D))});return}if(g[i]!==void 0){try{let n=g[i],p=l.join(a,n),F=(await import(I(p).href)).default;if(!F)throw new Error(`Component not found in ${n}`);let y=await F(),_=j(y),H=l.resolve(C,"index.html"),T=f.readFileSync(H,"utf8");T=T.replace('<div id="app"></div>',`<div id="app">${_}</div>`),T=T.replace("</body>",`<script type="module" src="/client.js"><\/script>
           <script type="module">
             const evtSource = new EventSource('/hmr');
             evtSource.onmessage = (event) => {
               if (event.data === 'reload') {
                 console.log('Changes detected. Reloading page...');
                 location.reload();
               }
             };
           <\/script>
           </body>`),e.setHeader("Content-Type","text/html"),e.end(T)}catch(n){console.error("\u274C Error rendering route:",n),e.statusCode=500,e.end("Internal Server Error")}return}e.statusCode=404,e.end("Not Found")}),u=t?.port||Number(process.env.PORT)||3e3;E.listen(u,()=>{console.log(`\u2705 Dev server running on http://localhost:${u}`)});function r(){for(let o of S)o.write(`data: reload

`)}f.watch(a,{recursive:!0},(o,e)=>{console.log(`File changed in pages: ${e} (event: ${o})`),r()});let v=l.resolve(c,".valzu/client.js");f.watchFile(v,(o,e)=>{o.mtime.getTime()!==e.mtime.getTime()&&(console.log("Client bundle changed."),r())})}var O=process.argv[1]||"",ne=O.includes("server.dev")?P:N;function L(){return s("div",{class:"container"},s("div",{class:"list"},s("p",{class:"title"},"VALZU'S LIST"),s("a",{href:"https://x.com/vvaltterisa",target:"_blank"},"X",s("span",{class:"link-icon"},"\u2197")),s("a",{href:"https://github.com/valtterisa",target:"_blank"},"GITHUB",s("span",{class:"link-icon"},"\u2197")),s("a",{href:"https://t.me/vsavonen",target:"_blank"},"TELEGRAM",s("span",{class:"link-icon"},"\u2197")),s("a",{href:"mailto:valtteri@bittive.com",target:"_blank"},"EMAIL",s("span",{class:"link-icon"},"\u2197"))),s("footer",{class:"footer"},s("p",{},"Made with"),s("a",{href:"https://github.com/valtterisa/valzu.js",target:"_blank"},"valzu.js")))}function z(){return L()}export{z as default};
